language: nodejs
node_js:
  - "8"
before_install:
  - export TZ=UTC

before_script:
  - npm install
  - npm install coveralls --save-dev

script:
  - npm run lint
  - npm run test
  - npm run coverage-ci
